version: '3.8'
services:
  claude-code:
    build: .
    image: claude-code-cli:latest
    volumes:
      - ./workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock   # Mount host Docker daemon socket for full access
    working_dir: /workspace
    tty: true           # Allocate a pseudo-TTY for interactive use
    stdin_open: true    # Keep STDIN open (needed for interactive CLI use)

